import Link from 'next/link'

import { Logo } from '@/components/logo'

const FOOTER_LINKS: ReadonlyArray<{ heading: string; links: ReadonlyArray<[string, string]> }> = [
  {
    heading: 'Product',
    links: [
      ['How it works', '#how-it-works'],
      ['Features', '#features'],
      ['Pricing', '/pricing'],
    ],
  },
  {
    heading: 'Account',
    links: [
      ['Sign in', '/sign-in'],
      ['Create account', '/sign-up'],
      ['Dashboard', '/dashboard'],
    ],
  },
]

export function SiteFooter() {
  return (
    <footer className="border-border/70 border-t">
      <div className="mx-auto w-full max-w-6xl px-4 py-12 sm:px-6">
        <div className="flex flex-col gap-10 sm:flex-row sm:justify-between">
          <div className="max-w-xs space-y-3">
            <Logo />
            <p className="text-muted-foreground text-sm leading-relaxed">
              Resume tailoring that will not invent experience you do not have.
            </p>
          </div>

          <div className="flex gap-12">
            {FOOTER_LINKS.map((group) => (
              <nav key={group.heading} aria-label={group.heading} className="space-y-3">
                <h2 className="text-xs font-medium uppercase tracking-wider">{group.heading}</h2>
                <ul className="space-y-2">
                  {group.links.map(([label, href]) => (
                    <li key={href}>
                      <Link
                        href={href}
                        className="text-muted-foreground hover:text-foreground rounded text-sm transition-colors"
                      >
                        {label}
                      </Link>
                    </li>
                  ))}
                </ul>
              </nav>
            ))}
          </div>
        </div>

        <p className="text-muted-foreground border-border/70 mt-10 border-t pt-6 text-xs">
          RoleFit is a portfolio project. Analyses are generated by a language model and are
          advisory, not a hiring decision.
        </p>
      </div>
    </footer>
  )
}
